add_newline = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bright-blue"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

